#pragma once

// GENERATED FILE — do not edit by hand. Regenerate with: python3 scripts/gen_schema_tokens.py
// Token strings derived from OpenUSD published schema data (https://raw.githubusercontent.com/PixarAnimationStudios/OpenUSD/dev/pxr/usd/.../generatedSchema.usda).

#include "freeusd/tf/token.hpp"

namespace freeusd::usdGeom::tokens {

/// Schema tokens (OpenUSD-shaped names; clean-room).
inline freeusd::tf::Token BasisCurves() { return freeusd::tf::Token("BasisCurves"); }
inline freeusd::tf::Token Boundable() { return freeusd::tf::Token("Boundable"); }
inline freeusd::tf::Token Camera() { return freeusd::tf::Token("Camera"); }
inline freeusd::tf::Token Capsule() { return freeusd::tf::Token("Capsule"); }
inline freeusd::tf::Token Capsule_1() { return freeusd::tf::Token("Capsule_1"); }
inline freeusd::tf::Token Cone() { return freeusd::tf::Token("Cone"); }
inline freeusd::tf::Token Cube() { return freeusd::tf::Token("Cube"); }
inline freeusd::tf::Token Curves() { return freeusd::tf::Token("Curves"); }
inline freeusd::tf::Token Cylinder() { return freeusd::tf::Token("Cylinder"); }
inline freeusd::tf::Token Cylinder_1() { return freeusd::tf::Token("Cylinder_1"); }
inline freeusd::tf::Token GeomModelAPI() { return freeusd::tf::Token("GeomModelAPI"); }
inline freeusd::tf::Token GeomSubset() { return freeusd::tf::Token("GeomSubset"); }
inline freeusd::tf::Token Gprim() { return freeusd::tf::Token("Gprim"); }
inline freeusd::tf::Token HermiteCurves() { return freeusd::tf::Token("HermiteCurves"); }
inline freeusd::tf::Token Imageable() { return freeusd::tf::Token("Imageable"); }
inline freeusd::tf::Token Mesh() { return freeusd::tf::Token("Mesh"); }
inline freeusd::tf::Token MotionAPI() { return freeusd::tf::Token("MotionAPI"); }
inline freeusd::tf::Token NurbsCurves() { return freeusd::tf::Token("NurbsCurves"); }
inline freeusd::tf::Token NurbsPatch() { return freeusd::tf::Token("NurbsPatch"); }
inline freeusd::tf::Token Plane() { return freeusd::tf::Token("Plane"); }
inline freeusd::tf::Token PointBased() { return freeusd::tf::Token("PointBased"); }
inline freeusd::tf::Token PointInstancer() { return freeusd::tf::Token("PointInstancer"); }
inline freeusd::tf::Token Points() { return freeusd::tf::Token("Points"); }
inline freeusd::tf::Token PrimvarsAPI() { return freeusd::tf::Token("PrimvarsAPI"); }
inline freeusd::tf::Token Scope() { return freeusd::tf::Token("Scope"); }
inline freeusd::tf::Token Sphere() { return freeusd::tf::Token("Sphere"); }
inline freeusd::tf::Token TetMesh() { return freeusd::tf::Token("TetMesh"); }
inline freeusd::tf::Token VisibilityAPI() { return freeusd::tf::Token("VisibilityAPI"); }
inline freeusd::tf::Token Xform() { return freeusd::tf::Token("Xform"); }
inline freeusd::tf::Token XformCommonAPI() { return freeusd::tf::Token("XformCommonAPI"); }
inline freeusd::tf::Token Xformable() { return freeusd::tf::Token("Xformable"); }
inline freeusd::tf::Token accelerations() { return freeusd::tf::Token("accelerations"); }
inline freeusd::tf::Token angularVelocities() { return freeusd::tf::Token("angularVelocities"); }
inline freeusd::tf::Token axis() { return freeusd::tf::Token("axis"); }
inline freeusd::tf::Token basis() { return freeusd::tf::Token("basis"); }
inline freeusd::tf::Token clippingPlanes() { return freeusd::tf::Token("clippingPlanes"); }
inline freeusd::tf::Token clippingRange() { return freeusd::tf::Token("clippingRange"); }
inline freeusd::tf::Token cornerIndices() { return freeusd::tf::Token("cornerIndices"); }
inline freeusd::tf::Token cornerSharpnesses() { return freeusd::tf::Token("cornerSharpnesses"); }
inline freeusd::tf::Token creaseIndices() { return freeusd::tf::Token("creaseIndices"); }
inline freeusd::tf::Token creaseLengths() { return freeusd::tf::Token("creaseLengths"); }
inline freeusd::tf::Token creaseSharpnesses() { return freeusd::tf::Token("creaseSharpnesses"); }
inline freeusd::tf::Token curveVertexCounts() { return freeusd::tf::Token("curveVertexCounts"); }
inline freeusd::tf::Token doubleSided() { return freeusd::tf::Token("doubleSided"); }
inline freeusd::tf::Token elementType() { return freeusd::tf::Token("elementType"); }
inline freeusd::tf::Token exposure() { return freeusd::tf::Token("exposure"); }
inline freeusd::tf::Token exposure_fStop() { return freeusd::tf::Token("exposure:fStop"); }
inline freeusd::tf::Token exposure_iso() { return freeusd::tf::Token("exposure:iso"); }
inline freeusd::tf::Token exposure_responsivity() { return freeusd::tf::Token("exposure:responsivity"); }
inline freeusd::tf::Token exposure_time() { return freeusd::tf::Token("exposure:time"); }
inline freeusd::tf::Token extent() { return freeusd::tf::Token("extent"); }
inline freeusd::tf::Token fStop() { return freeusd::tf::Token("fStop"); }
inline freeusd::tf::Token faceVaryingLinearInterpolation() { return freeusd::tf::Token("faceVaryingLinearInterpolation"); }
inline freeusd::tf::Token faceVertexCounts() { return freeusd::tf::Token("faceVertexCounts"); }
inline freeusd::tf::Token faceVertexIndices() { return freeusd::tf::Token("faceVertexIndices"); }
inline freeusd::tf::Token familyName() { return freeusd::tf::Token("familyName"); }
inline freeusd::tf::Token focalLength() { return freeusd::tf::Token("focalLength"); }
inline freeusd::tf::Token focusDistance() { return freeusd::tf::Token("focusDistance"); }
inline freeusd::tf::Token guideVisibility() { return freeusd::tf::Token("guideVisibility"); }
inline freeusd::tf::Token height() { return freeusd::tf::Token("height"); }
inline freeusd::tf::Token holeIndices() { return freeusd::tf::Token("holeIndices"); }
inline freeusd::tf::Token horizontalAperture() { return freeusd::tf::Token("horizontalAperture"); }
inline freeusd::tf::Token horizontalApertureOffset() { return freeusd::tf::Token("horizontalApertureOffset"); }
inline freeusd::tf::Token ids() { return freeusd::tf::Token("ids"); }
inline freeusd::tf::Token indices() { return freeusd::tf::Token("indices"); }
inline freeusd::tf::Token interpolateBoundary() { return freeusd::tf::Token("interpolateBoundary"); }
inline freeusd::tf::Token invisibleIds() { return freeusd::tf::Token("invisibleIds"); }
inline freeusd::tf::Token knots() { return freeusd::tf::Token("knots"); }
inline freeusd::tf::Token length() { return freeusd::tf::Token("length"); }
inline freeusd::tf::Token model_applyDrawMode() { return freeusd::tf::Token("model:applyDrawMode"); }
inline freeusd::tf::Token model_cardGeometry() { return freeusd::tf::Token("model:cardGeometry"); }
inline freeusd::tf::Token model_cardTextureXNeg() { return freeusd::tf::Token("model:cardTextureXNeg"); }
inline freeusd::tf::Token model_cardTextureXPos() { return freeusd::tf::Token("model:cardTextureXPos"); }
inline freeusd::tf::Token model_cardTextureYNeg() { return freeusd::tf::Token("model:cardTextureYNeg"); }
inline freeusd::tf::Token model_cardTextureYPos() { return freeusd::tf::Token("model:cardTextureYPos"); }
inline freeusd::tf::Token model_cardTextureZNeg() { return freeusd::tf::Token("model:cardTextureZNeg"); }
inline freeusd::tf::Token model_cardTextureZPos() { return freeusd::tf::Token("model:cardTextureZPos"); }
inline freeusd::tf::Token model_drawMode() { return freeusd::tf::Token("model:drawMode"); }
inline freeusd::tf::Token model_drawModeColor() { return freeusd::tf::Token("model:drawModeColor"); }
inline freeusd::tf::Token motion_blurScale() { return freeusd::tf::Token("motion:blurScale"); }
inline freeusd::tf::Token motion_nonlinearSampleCount() { return freeusd::tf::Token("motion:nonlinearSampleCount"); }
inline freeusd::tf::Token motion_velocityScale() { return freeusd::tf::Token("motion:velocityScale"); }
inline freeusd::tf::Token normals() { return freeusd::tf::Token("normals"); }
inline freeusd::tf::Token order() { return freeusd::tf::Token("order"); }
inline freeusd::tf::Token orientation() { return freeusd::tf::Token("orientation"); }
inline freeusd::tf::Token orientationsf() { return freeusd::tf::Token("orientationsf"); }
inline freeusd::tf::Token pointWeights() { return freeusd::tf::Token("pointWeights"); }
inline freeusd::tf::Token points() { return freeusd::tf::Token("points"); }
inline freeusd::tf::Token positions() { return freeusd::tf::Token("positions"); }
inline freeusd::tf::Token primvars_displayColor() { return freeusd::tf::Token("primvars:displayColor"); }
inline freeusd::tf::Token primvars_displayOpacity() { return freeusd::tf::Token("primvars:displayOpacity"); }
inline freeusd::tf::Token projection() { return freeusd::tf::Token("projection"); }
inline freeusd::tf::Token protoIndices() { return freeusd::tf::Token("protoIndices"); }
inline freeusd::tf::Token prototypes() { return freeusd::tf::Token("prototypes"); }
inline freeusd::tf::Token proxyPrim() { return freeusd::tf::Token("proxyPrim"); }
inline freeusd::tf::Token proxyVisibility() { return freeusd::tf::Token("proxyVisibility"); }
inline freeusd::tf::Token purpose() { return freeusd::tf::Token("purpose"); }
inline freeusd::tf::Token radius() { return freeusd::tf::Token("radius"); }
inline freeusd::tf::Token radiusBottom() { return freeusd::tf::Token("radiusBottom"); }
inline freeusd::tf::Token radiusTop() { return freeusd::tf::Token("radiusTop"); }
inline freeusd::tf::Token ranges() { return freeusd::tf::Token("ranges"); }
inline freeusd::tf::Token renderVisibility() { return freeusd::tf::Token("renderVisibility"); }
inline freeusd::tf::Token scales() { return freeusd::tf::Token("scales"); }
inline freeusd::tf::Token shutter_close() { return freeusd::tf::Token("shutter:close"); }
inline freeusd::tf::Token shutter_open() { return freeusd::tf::Token("shutter:open"); }
inline freeusd::tf::Token size() { return freeusd::tf::Token("size"); }
inline freeusd::tf::Token stereoRole() { return freeusd::tf::Token("stereoRole"); }
inline freeusd::tf::Token subdivisionScheme() { return freeusd::tf::Token("subdivisionScheme"); }
inline freeusd::tf::Token tangents() { return freeusd::tf::Token("tangents"); }
inline freeusd::tf::Token triangleSubdivisionRule() { return freeusd::tf::Token("triangleSubdivisionRule"); }
inline freeusd::tf::Token trimCurve_counts() { return freeusd::tf::Token("trimCurve:counts"); }
inline freeusd::tf::Token trimCurve_knots() { return freeusd::tf::Token("trimCurve:knots"); }
inline freeusd::tf::Token trimCurve_orders() { return freeusd::tf::Token("trimCurve:orders"); }
inline freeusd::tf::Token trimCurve_points() { return freeusd::tf::Token("trimCurve:points"); }
inline freeusd::tf::Token trimCurve_ranges() { return freeusd::tf::Token("trimCurve:ranges"); }
inline freeusd::tf::Token trimCurve_vertexCounts() { return freeusd::tf::Token("trimCurve:vertexCounts"); }
inline freeusd::tf::Token type() { return freeusd::tf::Token("type"); }
inline freeusd::tf::Token uForm() { return freeusd::tf::Token("uForm"); }
inline freeusd::tf::Token uKnots() { return freeusd::tf::Token("uKnots"); }
inline freeusd::tf::Token uOrder() { return freeusd::tf::Token("uOrder"); }
inline freeusd::tf::Token uRange() { return freeusd::tf::Token("uRange"); }
inline freeusd::tf::Token uVertexCount() { return freeusd::tf::Token("uVertexCount"); }
inline freeusd::tf::Token vForm() { return freeusd::tf::Token("vForm"); }
inline freeusd::tf::Token vKnots() { return freeusd::tf::Token("vKnots"); }
inline freeusd::tf::Token vOrder() { return freeusd::tf::Token("vOrder"); }
inline freeusd::tf::Token vRange() { return freeusd::tf::Token("vRange"); }
inline freeusd::tf::Token vVertexCount() { return freeusd::tf::Token("vVertexCount"); }
inline freeusd::tf::Token velocities() { return freeusd::tf::Token("velocities"); }
inline freeusd::tf::Token verticalAperture() { return freeusd::tf::Token("verticalAperture"); }
inline freeusd::tf::Token verticalApertureOffset() { return freeusd::tf::Token("verticalApertureOffset"); }
inline freeusd::tf::Token visibility() { return freeusd::tf::Token("visibility"); }
inline freeusd::tf::Token width() { return freeusd::tf::Token("width"); }
inline freeusd::tf::Token widths() { return freeusd::tf::Token("widths"); }
inline freeusd::tf::Token wrap() { return freeusd::tf::Token("wrap"); }
inline freeusd::tf::Token xformOpOrder() { return freeusd::tf::Token("xformOpOrder"); }

}  // namespace freeusd::usdGeom::tokens
