# CMake generated Testfile for 
# Source directory: /home/tim/freeusd
# Build directory: /home/tim/freeusd/build-verify
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[freeusd_selftest]=] "/home/tim/freeusd/build-verify/freeusd_selftest")
set_tests_properties([=[freeusd_selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;81;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_sdf_path_test]=] "/home/tim/freeusd/build-verify/freeusd_sdf_path_test")
set_tests_properties([=[freeusd_sdf_path_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;82;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_usd_smoke_test]=] "/home/tim/freeusd/build-verify/freeusd_usd_smoke_test")
set_tests_properties([=[freeusd_usd_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;83;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_usd_cross_language_test]=] "/home/tim/freeusd/build-verify/freeusd_usd_cross_language_test")
set_tests_properties([=[freeusd_usd_cross_language_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;84;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_usda_roundtrip_test]=] "/home/tim/freeusd/build-verify/freeusd_usda_roundtrip_test")
set_tests_properties([=[freeusd_usda_roundtrip_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;85;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_pcp_compose_test]=] "/home/tim/freeusd/build-verify/freeusd_pcp_compose_test")
set_tests_properties([=[freeusd_pcp_compose_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;86;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_stage_compose_test]=] "/home/tim/freeusd/build-verify/freeusd_stage_compose_test")
set_tests_properties([=[freeusd_stage_compose_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;87;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_stage_open_file_test]=] "/home/tim/freeusd/build-verify/freeusd_stage_open_file_test")
set_tests_properties([=[freeusd_stage_open_file_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;88;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_schema_tokens_bundle_test]=] "/home/tim/freeusd/build-verify/freeusd_schema_tokens_bundle_test")
set_tests_properties([=[freeusd_schema_tokens_bundle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;89;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_time_code_test]=] "/home/tim/freeusd/build-verify/freeusd_time_code_test")
set_tests_properties([=[freeusd_time_code_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;90;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_edit_target_test]=] "/home/tim/freeusd/build-verify/freeusd_edit_target_test")
set_tests_properties([=[freeusd_edit_target_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;91;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_sdf_layer_offset_test]=] "/home/tim/freeusd/build-verify/freeusd_sdf_layer_offset_test")
set_tests_properties([=[freeusd_sdf_layer_offset_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;92;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_sdf_asset_path_test]=] "/home/tim/freeusd/build-verify/freeusd_sdf_asset_path_test")
set_tests_properties([=[freeusd_sdf_asset_path_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;93;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_gf_range1d_test]=] "/home/tim/freeusd/build-verify/freeusd_gf_range1d_test")
set_tests_properties([=[freeusd_gf_range1d_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;94;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_gf_quatd_test]=] "/home/tim/freeusd/build-verify/freeusd_gf_quatd_test")
set_tests_properties([=[freeusd_gf_quatd_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;95;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_gf_bbox3d_test]=] "/home/tim/freeusd/build-verify/freeusd_gf_bbox3d_test")
set_tests_properties([=[freeusd_gf_bbox3d_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;96;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_ar_resolved_path_test]=] "/home/tim/freeusd/build-verify/freeusd_ar_resolved_path_test")
set_tests_properties([=[freeusd_ar_resolved_path_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;97;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_sdf_tokens_test]=] "/home/tim/freeusd/build-verify/freeusd_sdf_tokens_test")
set_tests_properties([=[freeusd_sdf_tokens_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;98;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_usd_tokens_test]=] "/home/tim/freeusd/build-verify/freeusd_usd_tokens_test")
set_tests_properties([=[freeusd_usd_tokens_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;99;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_smoke_test]=] "/home/tim/freeusd/build-verify/freeusd_c_smoke_test")
set_tests_properties([=[freeusd_c_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;106;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_usd_cross_language]=] "/home/tim/freeusd/build-verify/freeusd_c_usd_cross_language")
set_tests_properties([=[freeusd_c_usd_cross_language]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;114;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_composition_arcs]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_composition_arcs")
set_tests_properties([=[freeusd_c_stage_composition_arcs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;120;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_open_from_file]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_open_from_file")
set_tests_properties([=[freeusd_c_stage_open_from_file]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;128;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_relocate]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_relocate")
set_tests_properties([=[freeusd_c_stage_relocate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;134;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_prefix_substitution]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_prefix_substitution")
set_tests_properties([=[freeusd_c_stage_prefix_substitution]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;142;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_custom_layer_data]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_custom_layer_data")
set_tests_properties([=[freeusd_c_stage_custom_layer_data]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;150;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_variant]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_variant")
set_tests_properties([=[freeusd_c_stage_variant]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;156;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_prim_specifier]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_prim_specifier")
set_tests_properties([=[freeusd_c_stage_prim_specifier]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;164;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
add_test([=[freeusd_c_stage_layer_hints]=] "/home/tim/freeusd/build-verify/freeusd_c_stage_layer_hints")
set_tests_properties([=[freeusd_c_stage_layer_hints]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/tim/freeusd/CMakeLists.txt;170;add_test;/home/tim/freeusd/CMakeLists.txt;0;")
subdirs("src")
